<?php $this->headTitle('404 Not Found'); ?>

<section class="error-block">
    <div class="error-block__inner inner">
        <h1 class="error-block__not-found">Нет прав для доступа!
        </h1>
        <p class="error-block__number">403
        </p>
        <p class="error-block__text">У Вас нет разрешения на доступ к запрошенному URL на этом сервере
        </p>
        <p class="error-block__text">Перейдите на<a href="<?php echo $this->url('home');?>"> главную страницу</a>.
        </p>
    </div>
</section>
