<?php $this->headTitle('404 Not Found'); ?>

<section class="error-block">
    <div class="error-block__inner inner">
        <h1 class="error-block__not-found">Страница не найдена!
        </h1>
        <p class="error-block__number">404
        </p>
        <p class="error-block__text">Неправильно набран адрес или такой страницы не существует.
        </p>
        <p class="error-block__text">Перейдите на<a href="<?php echo $this->url('home');?>"> главную страницу</a> или воспользуйтесь поиском.
        </p>
    </div>
</section>
