<?php
/**
 * Created by PhpStorm.
 * User: KiisChivarino
 * Date: 05.04.19
 * Time: 12:04
 */ ?>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    <h3>
                        <?php
                        echo $this->isNew($this->url()) ? 'Добавление' : 'Редактирование';
                        echo ' базы товаров';
                        ?>
                    </h3>
                    <form class="form-horizontal form-label-left" <?php echo $this->isNew($this->url()) ? 'id="js-db-form"' : ''; ?> method="post" action="?">
                        <div class="form-group row">
                            <label
                                    class="control-label col-md-3 col-sm-3 col-xs-12" for="company-name">Наименование базы товаров <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="company-name" name="name" class="form-control col-md-7 col-xs-12" required="required"
                                       value="<?php echo !$this->isNew($this->url()) ? $this->escapeHtmlAttr($database->getName()) : ''; ?>"
                                />
                            </div>
                        </div>
                        <div class="form-group row">
                            <button class="buttonNext btn btn-success" <?php echo $this->isNew($this->url()) ? 'id="js-db-add"' : ''; ?> >
                                <?php echo 'Импортировать базу товаров'; ?>
                            </button>
                            <button class="buttonNext btn btn-success" data-toggle="modal" data-target="#setRnmModal" data-url="/lk/api/kkt/37/rnm">
                                <?php echo 'Добавить товар'; ?>
                            </button>
                        </div>

                    </form>
                    <?php echo $this->partial('office::db/product-list'); ?>
                </div>
            </div>
        </div>
    </div>
<?php echo $this->partial('office::db/product-add-modal'); ?>