<?php
/**
 * Created by PhpStorm.
 * User: KiisChivarino
 * Date: 06.05.19
 * Time: 15:47
 */ ?>
<!-- Modal -->
<div class="modal fade" id="importProductsModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="importProductsModalLabel">Импорт таблицы товаров</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal form-label-left" id="productsImport" enctype="multipart/form-data" method="post" action="?">
                    <div class="item form-group row">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="file">
                            Файл xlsx <span class="required">*</span>
                        </label>
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <input
                                    id="file"
                                    class="col-md-12 col-xs-12"
                                    name="file"
                                    type="file"
                                    required
                                    value=""
                            >
                        </div>
                    </div>
                    <div>
                        <a href="/docs/Apteka.xlsx" class="buttonNext btn btn-info">
                            <?php echo 'Скачать пример'; ?>
                        </a>
                    </div>
                    <div class="actionBar">
                        <button class="buttonNext btn btn-success js-office-product-import">
                            <?php echo 'Импортировать'; ?>
                        </button>
                    </div>
                </form>
                <div class="js-log"></div>
            </div>
        </div>
    </div>
</div>

