<?php
/**
 * Created by PhpStorm.
 * User: KiisChivarino
 * Date: 08.05.19
 * Time: 13:23
 */
/** @var Zend\View\Renderer\PhpRenderer $this */
/** @var \Auth\Entity\User[] $users */
/** @var \Permission\Entity\Role[] $roles */
/** @var array $paginator */
?>
<div class="">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h3>Список клиентов ЦТО
                    </h3>
                    <a href="<?php echo $this->url('office.customer.new'); ?>" class="btn btn-primary pull-right">Добавить</a>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <form action="?" method="get" class="form-inline">
                        <h5>Фильтр</h5>
                        <div class="form-group">
                            <input type="text" class="form-control" name="fio"
                                   value="<?php echo htmlspecialchars($paginator['query']['fio']) ?>" placeholder="ФИО">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="company"
                                   value="<?php echo htmlspecialchars($paginator['query']['company']) ?>"
                                   placeholder="Компания">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="email"
                                   value="<?php echo $this->escapeHtmlAttr($paginator['query']['email']) ?>"
                                   placeholder="E-mail">
                        </div>
                        <?php
                        /*
<!--                        <div class="form-group">-->
<!--                            <select name="role" class="form-control">-->
<!--                                <option>Не выбрано</option>-->
<!--                                --><?php
//                                foreach ($roles as $role) {
//                                    ?>
<!--                                    <option value="--><?php //echo $role->getId(); ?><!--" --><?php //echo $paginator['query']['email'] == $role->getId() ? 'selected' : ''; ?><!-->-->
<!--                                        --><?php //echo $role->getTitle(); ?>
<!--                                    </option>-->
<!--                                    --><?php
//                                }
//                                ?>
<!--                                ?>-->
<!--                            </select>-->
<!--                        </div>-->
                        */
                        ?>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary form-control">Применить</button>
                        </div>
                    </form>
                    <br>
                    <table class="table table-hover base-table table_client-name">
                        <thead>
                        <tr>
                            <th class="th">
                                <a href="<?php echo $this->url(
                                    'office.customer.list', [], [
                                        'sort' => 'id',
                                        'order' => $order
                                    ]
                                ); ?>">
                                    #
                                </a>
                                <?php if ($sortType === 'id') { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </th>
                            <th class="th">
                                <a href="<?php echo $this->url(
                                    'office.customer.list', [],
                                    [
                                        'sort' => 'lastName',
                                        'order' => $order
                                    ]
                                ); ?>">
                                    ФИО
                                </a>
                                <?php if ($sortType === 'lastName') { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </th>
                            <th class="th">
                                Компания
                                <?php if ($sortType === 'company') { ?>
                                    <span class="fa fa-chevron-down"></span>
                                <?php } ?>
                            </th>
                            <th class="th">
                                <a href="<?php echo $this->url(
                                    'office.customer.list', [],
                                    [
                                        'sort' => 'email',
                                        'order' => $order
                                    ]
                                ); ?>">
                                    Email
                                </a>
                                <?php if ($sortType === 'email') { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </th>
                            <th class="th">
                                <a href="<?php echo $this->url(
                                    'office.customer.list', [],
                                    [
                                        'sort' => 'phone',
                                        'order' => $order
                                    ]
                                ); ?>">
                                    Телефон
                                </a>
                                <?php if ($sortType === 'phone') { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </th>
                            <!--                            <th class="th">-->
                            <!--                                Роли-->
                            <!--                                --><?php //if ($sortType === 'userRole') { ?>
                            <!--                                    <span class="fa fa-chevron---><?php //echo $chevron; ?><!--"></span>-->
                            <!--                                --><?php //} ?>
                            <!--                            </th>-->
                            <!--                            <th class="th">-->
                            <!--                                <a href="--><?php //echo $this->url(
                            //                                    'office.customer.list', [],
                            //                                    [
                            //                                        'sort' => 'dateCreate',
                            //                                        'order' => $order
                            //                                    ]
                            //                                ); ?><!--">-->
                            <!--                                    Дата регистрации-->
                            <!--                                </a>-->
                            <!--                                --><?php //if ($sortType === 'dateCreate') { ?>
                            <!--                                    <span class="fa fa-chevron---><?php //echo $chevron; ?><!--"></span>-->
                            <!--                                --><?php //} ?>
                            <!--                            </th>-->
                            <th class="th">
                                <a href="<?php echo $this->url(
                                    'office.customer.list', [],
                                    [
                                        'sort' => 'dateLastAuth',
                                        'order' => $order
                                    ]
                                ); ?>">
                                    Дата авториз.
                                </a>
                                <?php if ($sortType === 'dateLastAuth') { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </th>
                            <th class="th">
                                <a href="<?php echo $this->url(
                                    'office.customer.list', [],
                                    [
                                        'sort' => 'isConfirmed',
                                        'order' => $order
                                    ]
                                ); ?>">
                                    Статус
                                </a>
                                <?php if ($sortType === 'isConfirmed') { ?>
                                    <span class="fa fa-chevron-<?php echo $chevron; ?>"></span>
                                <?php } ?>
                            </th>
                            <th class="th">
                                <div class="pull-right"></div>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach ($users as $user) {
                            ?>
                            <tr>
                                <th scope="row"><?php echo $user->getId(); ?></th>
                                <td class="td">
                                    <?php echo $user->getFIO(); ?>
                                </td>
                                <td class="td long">
                                    <?php
                                    $companyArr = [];
                                    /** @var \Office\Entity\LkCompany $company */
                                    foreach ($user->getCompany() as $company) {
                                        echo !$company->getIsDeleted() ? $this->escapeHtml($company->getName()).'<br />' : '';
                                    }
                                    echo implode(',', $companyArr);
                                    ?>
                                </td>
                                <td class="td">
                                    <a href="mailto:<?php echo $this->escapeHtmlAttr($user->getEmail()); ?>"><?php echo $this->escapeHtml($user->getEmail()); ?></a>
                                </td>
                                <td class="td">
                                    <a target="_blank" href="tel:<?php echo str_replace(
                                        [
                                            '(',
                                            ')',
                                            ' ',
                                            '-'
                                        ], '', $user->getPhone()
                                    ); ?>"><?php echo $user->getPhone(); ?></a>
                                </td>
                                <!--                                <td class="td">-->
                                <!--                                    --><?php
                                //                                    $userRoles = [];
                                //                                    /** @var \Auth\Entity\UserHasRole $role */
                                //                                    foreach ($user->getUserRoles() as $role) {
                                //                                        $userRoles[] = $roles[$role->getRoleName()]->getTitle();
                                //                                    }
                                //                                    echo implode(', ', $userRoles);
                                //                                    ?>
                                <!--                                </td>-->
                                <!--                                <td class="td">-->
                                <!--                                    --><?php //echo $user->getDateCreate()->format('d.m.Y H:i:s'); ?>
                                <!--                                </td>-->
                                <td class="td">
                                    <?php echo $user->getDateLastAuth() ? $this->escapeHtml($user->getDateLastAuth()->format('d.m.y')) : '-'; ?>
                                </td>
                                <td class="td">
                                    <?php echo $user->getIsConfirmed() ? 'Активен' : 'Не подтвержден'; ?>
                                </td>
                                <td class="td">
                                    <div class="pull-right">
                                        <!--                                    --><?php //if ($user->getIsConfirmed()) { ?>
                                        <!--                                        <a href="--><?php //echo $this->url(
                                        //                                            'office.customer.login', [
                                        //                                                'id' => $user->getId(),
                                        //                                            ]
                                        //                                        ) ?><!--" class="btn btn-primary">Авторизоваться</a>-->
                                        <!--                                    --><?php //} ?>
                                        <button class="btn btn-danger js-office-element-remove"
                                                data-url="<?php echo $this->url('office.customer.delete', ['id' => $user->getId()]); ?>"
                                                title="Удаление из списка клиентов ЦТО">
                                            <span class="glyphicon glyphicon-remove-sign"></span>
                                        </button>
                                    </div>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                        </tbody>
                    </table>
                    <?php echo $this->paginator($paginator, 'office::paginator'); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php //echo __FILE__;?>
