<?php
/**
 * Created by PhpStorm.
 * User: KiisChivarino
 * Date: 08.05.19
 * Time: 13:22
 */
?>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <h3>
                    <?php
                    echo 'Добавление клиента ЦТО';
                    ?>
                </h3>
                <form class="form-horizontal form-label-left" action="<?php echo $this->url('office.customer.add'); ?>" method="post">
                    <div class="form-group row">
                        <label
                                class="control-label col-md-3 col-sm-3 col-xs-12" for="company-name">Введите email пользователя <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="email" required name="email" class="form-control col-md-7 col-xs-12" placeholder="example@email.ru" value=""/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label
                                class="control-label col-md-3 col-sm-3 col-xs-12" for="company">Компания <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select class="js-example-basic-single select2-hidden-accessible_width" name="company" id="company" required>
                                <?php /** @var \Office\Entity\LkCompany $company */
                                foreach ($data['companies'] as $company) {
                                    ?>
                                    <option
                                            value="<?php echo $company->getId(); ?>"
                                    ><?php echo $company->getName(); ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="actionBar">
                        <button type="submit" name="button" class="buttonNext btn btn-success">Добавить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>